//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonheur.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItem
    {
        public int PurchaseItemID { get; set; }
        public int PurchaseCategoryID { get; set; }
        public decimal UnitCount { get; set; }
        public decimal Amount { get; set; }
        public int PurchaseID { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        public virtual PurchaseCategory PurchaseCategory { get; set; }
    }
}
