//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonheur.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int SalaryID { get; set; }
        public System.DateTime SalaryDate { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public decimal Rate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
